<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PackageSeeder extends Seeder
{
    public function run()
    {
        Package::truncate();

        $packages = [
            [
                'title' => 'Great Migration Safari',
                'short_description' => 'Experience the spectacular Great Migration in the Serengeti.',
                'overview' => "Join us on an unforgettable journey through the Serengeti and Ngorongoro Crater. Witness the massive herds of wildebeest and zebras, encounter the Big Five, and experience the beauty of Tanzania's wildlife.",
                'price' => 3200.00,
                'duration' => '8 Days / 7 Nights',
                'location' => 'Serengeti National Park, Ngorongoro Crater',
                'rating_display' => '4.9 (55 Reviews)',
                'display_tags' => 'Migration, Big Five, Popular',
                'status' => 'published',
                'inclusions' => ['Airport transfers', 'Luxury lodge accommodation', 'All meals & drinks (local)', 'Park fees', 'Experienced guide', '4x4 vehicle'],
                'exclusions' => ['International flights', 'Visa fees', 'Gratuities', 'Travel insurance'],
                'highlights' => [
                    ['title' => 'Migration Spectacle', 'description' => 'Witness the river crossings (seasonal).'],
                    ['title' => 'Big Five Guaranteed', 'description' => 'High chances of spotting lion, leopard, elephant, rhino, buffalo.'],
                    ['title' => 'Ngorongoro Crater', 'description' => 'Explore the unique ecosystem of the caldera.'],
                ],
                'itinerary' => [
                    ['title' => 'Day 1: Arrival Arusha', 'description' => 'Transfer to Arusha Coffee Lodge.', 'accommodation' => 'Arusha Coffee Lodge'],
                    ['title' => 'Day 2-4: Serengeti', 'description' => 'Fly to Serengeti, multiple game drives focusing on migration hotspots.', 'accommodation' => 'Serengeti Migration Camp'],
                    ['title' => 'Day 5: Ngorongoro Transfer', 'description' => 'Scenic drive to Ngorongoro Conservation Area.', 'accommodation' => 'Ngorongoro Serena Safari Lodge'],
                    ['title' => 'Day 6: Ngorongoro Crater', 'description' => 'Full day game drive inside the crater.', 'accommodation' => 'Ngorongoro Serena Safari Lodge'],
                    ['title' => 'Day 7: Tarangire', 'description' => 'Drive to Tarangire National Park, afternoon game drive.', 'accommodation' => 'Tarangire Treetops'],
                    ['title' => 'Day 8: Departure', 'description' => 'Morning game drive, transfer to Kilimanjaro Airport (JRO).', 'accommodation' => null],
                ],
                'destinations' => ['serengeti', 'ngorongoro', 'tarangire'],
                'safari_types' => ['luxury', 'migration', 'group'],
                'min_pax' => 2,
                'max_pax' => 6,
                'is_featured' => true,
                'show_popular_tag' => true,
                'hero_image' => 'package-images/placeholder_hero.jpg',
                'gallery_images' => ['package-gallery/placeholder_1.jpg', 'package-gallery/placeholder_2.jpg'],
            ],
            [
                'title' => 'Tanzania Budget Camping Safari',
                'short_description' => 'Affordable adventure exploring Tarangire, Serengeti & Ngorongoro.',
                'overview' => 'Experience the best of Tanzania\'s Northern Circuit on a budget-friendly camping safari. Sleep under the stars and enjoy thrilling game drives without breaking the bank.',
                'price' => 1550.00,
                'duration' => '6 Days / 5 Nights',
                'location' => 'Tarangire, Serengeti, Ngorongoro',
                'rating_display' => '4.5 (30 Reviews)',
                'display_tags' => 'Budget, Camping, Adventure',
                'status' => 'published',
                'inclusions' => ['Park fees', 'Camping fees', 'Meals (cooked by chef)', '4x4 vehicle', 'Guide/Driver', 'Camping equipment (tent, mattress)'],
                'exclusions' => ['Sleeping bag', 'International flights', 'Visa', 'Tips', 'Drinks'],
                'highlights' => [
                    ['title' => 'Affordable Wildlife Viewing', 'description' => 'See incredible animals at a lower cost.'],
                    ['title' => 'Authentic Camping', 'description' => 'Experience the sounds of the bush at night.'],
                    ['title' => 'Professional Crew', 'description' => 'Includes a guide and a dedicated cook.'],
                ],
                'itinerary' => [
                     ['title' => 'Day 1: Tarangire', 'description' => 'Drive to Tarangire, afternoon game drive.', 'accommodation' => 'Public Campsite'],
                     ['title' => 'Day 2-3: Serengeti', 'description' => 'Drive to Serengeti, game drives.', 'accommodation' => 'Seronera Public Campsite'],
                     ['title' => 'Day 4: Ngorongoro', 'description' => 'Game drive en route to Ngorongoro rim.', 'accommodation' => 'Simba Public Campsite'],
                     ['title' => 'Day 5: Ngorongoro Crater', 'description' => 'Morning crater tour, drive back towards Arusha.', 'accommodation' => 'Twiga Public Campsite'],
                     ['title' => 'Day 6: Departure', 'description' => 'Return to Arusha.', 'accommodation' => null],
                 ],
                'destinations' => ['tarangire', 'serengeti', 'ngorongoro'],
                'safari_types' => ['budget', 'camping', 'group'],
                'min_pax' => 2,
                'max_pax' => 7,
                'is_featured' => false,
                'show_popular_tag' => false,
                'hero_image' => 'package-images/placeholder_hero_budget.jpg',
                'gallery_images' => ['package-gallery/placeholder_budget_1.jpg'],
            ],
            [
                'title' => 'Kilimanjaro Climb - Lemosho Route',
                'short_description' => 'Scenic 8-day trek to the roof of Africa via the Lemosho route.',
                'overview' => 'Challenge yourself with a trek up Mount Kilimanjaro, the highest freestanding mountain in the world. The Lemosho route offers stunning scenery and excellent acclimatization.',
                'price' => 2800.00,
                'duration' => '8 Days / 7 Nights',
                'location' => 'Mount Kilimanjaro National Park',
                'rating_display' => '4.7 (42 Reviews)',
                'display_tags' => 'Trekking, Kilimanjaro, Challenge',
                'status' => 'published',
                'inclusions' => ['Airport transfers', 'Hotel before/after climb (2 nights)', 'Park fees', 'Rescue fees', 'Mountain guide & porters', 'All meals on trek', 'Camping equipment'],
                'exclusions' => ['International flights', 'Visa', 'Tips for crew', 'Personal gear rental', 'Travel insurance'],
                'highlights' => [
                    ['title' => 'Summit Success', 'description' => 'Reach Uhuru Peak, the highest point in Africa.'],
                    ['title' => 'Scenic Lemosho Route', 'description' => 'Beautiful views and good acclimatization profile.'],
                    ['title' => 'Experienced Crew', 'description' => 'Professional guides and porters ensure safety.'],
                ],
                'itinerary' => [
                     ['title' => 'Day 1: Arrival', 'description' => 'Arrive JRO, transfer to Moshi hotel.', 'accommodation' => 'Hotel in Moshi'],
                     ['title' => 'Day 2: Trek Start (Lemosho Gate to Mti Mkubwa)', 'description' => 'Drive to gate, begin trek through rainforest.', 'accommodation' => 'Mti Mkubwa Camp'],
                     ['title' => 'Day 3: Shira 1 Camp', 'description' => 'Trek across the Shira Plateau.', 'accommodation' => 'Shira 1 Camp'],
                     ['title' => 'Day 4: Shira 2 Camp via Lava Tower', 'description' => 'Acclimatization day, climb high sleep low.', 'accommodation' => 'Shira 2 Camp'],
                     ['title' => 'Day 5: Barranco Camp', 'description' => 'Descend into the Barranco Valley.', 'accommodation' => 'Barranco Camp'],
                     ['title' => 'Day 6: Karanga Camp', 'description' => 'Conquer the Barranco Wall.', 'accommodation' => 'Karanga Camp'],
                     ['title' => 'Day 7: Barafu Camp (Base Camp)', 'description' => 'Reach base camp, prepare for summit.', 'accommodation' => 'Barafu Camp'],
                     ['title' => 'Day 8: Summit Day & Descent', 'description' => 'Midnight start for summit, descend to Mweka Camp.', 'accommodation' => 'Mweka Camp'],
                     ['title' => 'Day 9: Descent & Departure', 'description' => 'Descend to Mweka Gate, transfer to hotel/airport.', 'accommodation' => 'Hotel in Moshi (or depart)'],
                 ],
                'destinations' => ['kilimanjaro'],
                'safari_types' => ['trekking', 'challenge'],
                'min_pax' => 1,
                'max_pax' => 12,
                'is_featured' => true,
                'show_popular_tag' => false,
                'hero_image' => 'package-images/kili_hero.jpg',
                'gallery_images' => [],
            ],
            [
                'title' => 'Zanzibar Beach Escape',
                'short_description' => 'Relax on the white sand beaches of Zanzibar.',
                'overview' => 'Unwind after your safari or simply escape to paradise. Enjoy the turquoise waters, spice farms, and historic Stone Town of Zanzibar.',
                'price' => 950.00,
                'duration' => '5 Days / 4 Nights',
                'location' => 'Zanzibar (Nungwi/Kendwa)',
                'rating_display' => null,
                'display_tags' => 'Beach, Relaxation, Zanzibar',
                'status' => 'draft',
                'inclusions' => ['Airport transfers (ZNZ)', 'Beachfront hotel accommodation', 'Breakfast daily', 'Spice tour'],
                'exclusions' => ['Flights to/from Zanzibar', 'Lunches & dinners', 'Optional activities (diving, snorkeling)', 'Visa'],
                'highlights' => [
                    ['title' => 'Pristine Beaches', 'description' => 'Relax on the famous white sand beaches.'],
                    ['title' => 'Spice Farm Tour', 'description' => 'Discover the spices that make Zanzibar famous.'],
                    ['title' => 'Stone Town Exploration', 'description' => 'Optional visit to the historic UNESCO site.'],
                ],
                 'itinerary' => [
                     ['title' => 'Day 1: Arrival Zanzibar', 'description' => 'Transfer to your beach hotel.', 'accommodation' => 'Beach Hotel'],
                     ['title' => 'Day 2-3: Beach Relaxation', 'description' => 'Enjoy the beach, swimming, and optional water sports.', 'accommodation' => 'Beach Hotel'],
                     ['title' => 'Day 4: Spice Tour', 'description' => 'Morning spice farm tour, afternoon free.', 'accommodation' => 'Beach Hotel'],
                     ['title' => 'Day 5: Departure', 'description' => 'Transfer to Zanzibar Airport (ZNZ).', 'accommodation' => null],
                 ],
                'destinations' => ['zanzibar'],
                'safari_types' => ['beach', 'relaxation'],
                'min_pax' => 1,
                'max_pax' => null,
                'is_featured' => false,
                'show_popular_tag' => false,
                'hero_image' => null,
                'gallery_images' => [],
            ],
            [
                'title' => 'Luxury Fly-in Safari',
                'short_description' => 'Explore remote Serengeti & Tarangire via scenic flights.',
                'overview' => 'Maximize your wildlife viewing time with convenient flights between luxury camps in Tarangire and the Serengeti. Enjoy exclusive game drives and unparalleled comfort.',
                'price' => 4800.00,
                'duration' => '7 Days / 6 Nights',
                'location' => 'Tarangire, Serengeti',
                'rating_display' => '5.0 (15 Reviews)',
                'display_tags' => 'Luxury, Fly-in, Exclusive',
                'status' => 'published',
                'inclusions' => ['Internal flights (Arusha-Tarangire, Tarangire-Serengeti, Serengeti-Arusha)', 'Luxury tented camp accommodation', 'All meals & premium drinks', 'Private game drives', 'Park fees', 'Laundry service'],
                'exclusions' => ['International flights', 'Visa', 'Gratuities'],
                'highlights' => [
                    ['title' => 'Aerial Views', 'description' => 'Spectacular views during internal flights.'],
                    ['title' => 'Remote Luxury Camps', 'description' => 'Stay in exclusive, high-end camps.'],
                    ['title' => 'Time Efficient', 'description' => 'Less travel time, more safari time.'],
                ],
                'itinerary' => [
                    ['title' => 'Day 1: Fly to Tarangire', 'description' => 'Fly from Arusha to Tarangire, transfer to camp, afternoon game drive.', 'accommodation' => 'Oliver\'s Camp'],
                    ['title' => 'Day 2: Tarangire Exploration', 'description' => 'Full day game drives in Tarangire.', 'accommodation' => 'Oliver\'s Camp'],
                    ['title' => 'Day 3: Fly to Serengeti', 'description' => 'Morning game drive, fly to Serengeti (Seronera), transfer to camp.', 'accommodation' => 'Namiri Plains'],
                    ['title' => 'Day 4-5: Serengeti Wildlife', 'description' => 'Explore the Seronera Valley, known for big cats.', 'accommodation' => 'Namiri Plains'],
                    ['title' => 'Day 6: Walking Safari Option', 'description' => 'Morning game drive or optional walking safari (extra cost).', 'accommodation' => 'Namiri Plains'],
                    ['title' => 'Day 7: Fly to Arusha', 'description' => 'Morning activity, fly back to Arusha.', 'accommodation' => null],
                ],
                'destinations' => ['tarangire', 'serengeti'],
                'safari_types' => ['luxury', 'fly-in'],
                'min_pax' => 2,
                'max_pax' => 4,
                'is_featured' => true,
                'show_popular_tag' => false,
                'hero_image' => 'package-images/fly_in_hero.jpg',
                'gallery_images' => [],
            ],
            [
                'title' => 'Southern Tanzania Adventure (Selous & Ruaha)',
                'short_description' => 'Explore the wild, remote parks of Southern Tanzania.',
                'overview' => 'Get off the beaten track in Selous Game Reserve (Nyerere NP) and Ruaha National Park. Experience boat safaris, walking safaris, and vast, untouched wilderness.',
                'price' => 3900.00,
                'duration' => '9 Days / 8 Nights',
                'location' => 'Selous Game Reserve, Ruaha National Park',
                'rating_display' => '4.8 (22 Reviews)',
                'display_tags' => 'Remote, Wild, Boat Safari',
                'status' => 'published',
                'inclusions' => ['Internal flights (Dar-Selous, Selous-Ruaha, Ruaha-Dar)', 'Lodge/Tented Camp accommodation', 'All meals', 'Shared game drives', 'Boat safaris in Selous', 'Walking safaris', 'Park fees'],
                'exclusions' => ['International flights (to Dar es Salaam)', 'Visa', 'Drinks', 'Gratuities'],
                'highlights' => [
                    ['title' => 'Boat Safari on Rufiji River', 'description' => 'Unique perspective, see hippos, crocodiles, birds.'],
                    ['title' => 'Ruaha\'s Wild Dogs', 'description' => 'Good chances of spotting endangered wild dogs.'],
                    ['title' => 'Remote Wilderness', 'description' => 'Fewer crowds than the Northern Circuit.'],
                ],
                'itinerary' => [
                     ['title' => 'Day 1: Fly to Selous', 'description' => 'Fly from Dar es Salaam to Selous, transfer to camp.', 'accommodation' => 'Selous Impala Camp'],
                     ['title' => 'Day 2-3: Selous Activities', 'description' => 'Game drives, boat safari, optional walking safari.', 'accommodation' => 'Selous Impala Camp'],
                     ['title' => 'Day 4: Fly to Ruaha', 'description' => 'Fly from Selous to Ruaha, transfer to lodge.', 'accommodation' => 'Ruaha River Lodge'],
                     ['title' => 'Day 5-7: Ruaha Exploration', 'description' => 'Game drives exploring the diverse landscapes of Ruaha.', 'accommodation' => 'Ruaha River Lodge'],
                     ['title' => 'Day 8: Walking Safari', 'description' => 'Morning walking safari, afternoon game drive.', 'accommodation' => 'Ruaha River Lodge'],
                     ['title' => 'Day 9: Fly to Dar', 'description' => 'Morning activity, fly back to Dar es Salaam.', 'accommodation' => null],
                 ],
                'destinations' => ['selous', 'ruaha'],
                'safari_types' => ['adventure', 'remote', 'fly-in'],
                'min_pax' => 2,
                'max_pax' => 6,
                'is_featured' => false,
                'show_popular_tag' => false,
                'hero_image' => 'package-images/southern_hero.jpg',
                'gallery_images' => [],
            ],
            [
                'title' => 'Short & Sweet Tarangire & Ngorongoro',
                'short_description' => 'A quick 4-day safari hitting two iconic parks.',
                'overview' => 'Perfect for those short on time, this safari covers the elephant haven of Tarangire and the breathtaking Ngorongoro Crater.',
                'price' => 1850.00,
                'duration' => '4 Days / 3 Nights',
                'location' => 'Tarangire, Ngorongoro Crater',
                'rating_display' => '4.6 (35 Reviews)',
                'display_tags' => 'Short Safari, Big Five, Elephants',
                'status' => 'published',
                'inclusions' => ['Airport transfer (arrival)', 'Mid-range lodge accommodation', 'All meals on safari', 'Park fees', 'Experienced guide', '4x4 vehicle', 'Crater service fee'],
                'exclusions' => ['International flights', 'Visa', 'Departure transfer', 'Drinks', 'Gratuities'],
                'highlights' => [
                    ['title' => 'Tarangire Elephants', 'description' => 'Famous for its large elephant herds.'],
                    ['title' => 'Ngorongoro Crater Floor', 'description' => 'Dense wildlife population in the caldera.'],
                    ['title' => 'Efficient Itinerary', 'description' => 'Covers key highlights quickly.'],
                ],
                 'itinerary' => [
                     ['title' => 'Day 1: Arusha to Tarangire', 'description' => 'Drive to Tarangire, afternoon game drive.', 'accommodation' => 'Tarangire Sopa Lodge'],
                     ['title' => 'Day 2: Tarangire to Ngorongoro', 'description' => 'Morning game drive in Tarangire, drive to Ngorongoro Conservation Area.', 'accommodation' => 'Ngorongoro Rhino Lodge'],
                     ['title' => 'Day 3: Ngorongoro Crater Tour', 'description' => 'Full day game drive in the Ngorongoro Crater.', 'accommodation' => 'Ngorongoro Rhino Lodge'],
                     ['title' => 'Day 4: Return to Arusha', 'description' => 'Drive back to Arusha, drop off at hotel or airport (JRO).', 'accommodation' => null],
                 ],
                'destinations' => ['tarangire', 'ngorongoro'],
                'safari_types' => ['short', 'lodge', 'budget'],
                'min_pax' => 2,
                'max_pax' => 7,
                'is_featured' => true,
                'show_popular_tag' => false,
                'hero_image' => 'package-images/short_safari_hero.jpg',
                'gallery_images' => [],
            ],
            [
                'title' => 'Cultural Immersion & Wildlife Safari',
                'short_description' => 'Combine wildlife viewing with authentic cultural experiences.',
                'overview' => 'Visit Lake Manyara for tree-climbing lions, explore Ngorongoro, and spend time with local Maasai and Hadzabe communities for a deeper understanding of Tanzania.',
                'price' => 2600.00,
                'duration' => '7 Days / 6 Nights',
                'location' => 'Lake Manyara, Lake Eyasi, Ngorongoro',
                'rating_display' => '4.7 (18 Reviews)',
                'display_tags' => 'Cultural, Maasai, Hadzabe',
                'status' => 'published',
                'inclusions' => ['Lodge/Tented Camp accommodation', 'All meals', 'Park fees', 'Cultural visit fees', 'Guide', '4x4 vehicle'],
                'exclusions' => ['International flights', 'Visa', 'Drinks', 'Gratuities'],
                'highlights' => [
                    ['title' => 'Hadzabe Hunter-Gatherers', 'description' => 'Learn traditional hunting techniques.'],
                    ['title' => 'Maasai Village Visit', 'description' => 'Experience Maasai culture and traditions.'],
                    ['title' => 'Lake Manyara Wildlife', 'description' => 'See flamingos and tree-climbing lions.'],
                ],
                'itinerary' => [
                     ['title' => 'Day 1: Arusha to Lake Manyara', 'description' => 'Drive to Mto wa Mbu, cultural tour & market visit, drive to lodge.', 'accommodation' => 'Manyara Serena Safari Lodge'],
                     ['title' => 'Day 2: Lake Manyara Game Drive', 'description' => 'Full day game drive in Lake Manyara National Park.', 'accommodation' => 'Manyara Serena Safari Lodge'],
                     ['title' => 'Day 3: Lake Eyasi (Hadzabe & Datoga)', 'description' => 'Drive to Lake Eyasi, visit Hadzabe & Datoga tribes.', 'accommodation' => 'Kisima Ngeda Tented Camp'],
                     ['title' => 'Day 4: Morning with Hadzabe, transfer to Karatu', 'description' => 'Early morning hunt with Hadzabe, drive to Karatu.', 'accommodation' => 'Ngorongoro Farm House'],
                     ['title' => 'Day 5: Ngorongoro Crater', 'description' => 'Full day game drive in the crater.', 'accommodation' => 'Ngorongoro Farm House'],
                     ['title' => 'Day 6: Maasai Village & Return', 'description' => 'Visit a Maasai Boma, drive back to Arusha.', 'accommodation' => 'Arusha Hotel (own arrangement or add-on)'],
                     ['title' => 'Day 7: Departure', 'description' => 'Transfer to JRO airport.', 'accommodation' => null],
                 ],
                'destinations' => ['manyara', 'eyasi', 'ngorongoro'],
                'safari_types' => ['cultural', 'group', 'lodge'],
                'min_pax' => 2,
                'max_pax' => 6,
                'is_featured' => false,
                'show_popular_tag' => false,
                'hero_image' => 'package-images/cultural_hero.jpg',
                'gallery_images' => [],
            ],
            [
                'title' => 'Family Fun Safari & Zanzibar Combo',
                'short_description' => 'Kid-friendly safari adventures plus beach relaxation.',
                'overview' => 'A perfect balance for families, featuring engaging wildlife encounters in Tarangire and Ngorongoro, followed by beach time and fun activities in Zanzibar.',
                'price' => 3500.00,
                'duration' => '10 Days / 9 Nights',
                'location' => 'Tarangire, Ngorongoro, Zanzibar',
                'rating_display' => '4.9 (25 Reviews)',
                'display_tags' => 'Family, Kids, Beach Combo',
                'status' => 'published',
                'inclusions' => ['Family-friendly lodge/hotel accommodation', 'Most meals (check specifics)', 'Park fees', 'Crater fee', 'Guide', '4x4 vehicle', 'Flight Arusha-Zanzibar', 'Zanzibar transfers', 'Some Zanzibar activities (e.g., Spice Tour)'],
                'exclusions' => ['International flights', 'Visa', 'Some meals', 'Optional activities', 'Gratuities'],
                'highlights' => [
                    ['title' => 'Interactive Activities', 'description' => 'Engaging experiences suitable for children.'],
                    ['title' => 'Wildlife & Beach Mix', 'description' => 'Combines adventure with relaxation.'],
                    ['title' => 'Family Accommodations', 'description' => 'Stays selected for family suitability.'],
                ],
                'itinerary' => [
                     ['title' => 'Day 1: Arrival Arusha', 'description' => 'Transfer to family lodge.', 'accommodation' => 'Rivertrees Country Inn'],
                     ['title' => 'Day 2: Tarangire', 'description' => 'Drive to Tarangire, game drive.', 'accommodation' => 'Maramboi Tented Lodge'],
                     ['title' => 'Day 3: Tarangire Fun', 'description' => 'Game drive, maybe lodge activities.', 'accommodation' => 'Maramboi Tented Lodge'],
                     ['title' => 'Day 4: Ngorongoro', 'description' => 'Drive to Ngorongoro, optional Maasai visit.', 'accommodation' => 'Ngorongoro Serena Safari Lodge (Family Room)'],
                     ['title' => 'Day 5: Ngorongoro Crater', 'description' => 'Crater game drive (limited hours often better for kids).', 'accommodation' => 'Ngorongoro Serena Safari Lodge'],
                     ['title' => 'Day 6: Fly to Zanzibar', 'description' => 'Drive to Arusha Airport (ARK), fly to Zanzibar, transfer to beach hotel.', 'accommodation' => 'Breezes Beach Club & Spa'],
                     ['title' => 'Day 7-8: Zanzibar Beach Fun', 'description' => 'Relax, swim, build sandcastles.', 'accommodation' => 'Breezes Beach Club & Spa'],
                     ['title' => 'Day 9: Spice Tour & Stone Town', 'description' => 'Morning spice tour, optional afternoon Stone Town visit.', 'accommodation' => 'Breezes Beach Club & Spa'],
                     ['title' => 'Day 10: Departure', 'description' => 'Transfer to Zanzibar Airport (ZNZ).', 'accommodation' => null],
                 ],
                'destinations' => ['tarangire', 'ngorongoro', 'zanzibar'],
                'safari_types' => ['family', 'beach', 'lodge'],
                'min_pax' => 3,
                'max_pax' => 5,
                'is_featured' => true,
                'show_popular_tag' => true,
                'hero_image' => 'package-images/family_hero.jpg',
                'gallery_images' => [],
            ],
            [
                'title' => 'Honeymoon Special: Luxury & Romance',
                'short_description' => 'Ultimate romantic getaway combining safari and beach.',
                'overview' => 'Indulge in a luxurious honeymoon with private dinners, stunning lodges in Serengeti, and a secluded beach escape on Pemba Island (or Zanzibar).',
                'price' => 6500.00,
                'duration' => '12 Days / 11 Nights',
                'location' => 'Serengeti, Pemba Island (or Zanzibar)',
                'rating_display' => '5.0 (10 Reviews)',
                'display_tags' => 'Honeymoon, Luxury, Romantic, Beach',
                'status' => 'published',
                'inclusions' => ['Top-tier luxury accommodation', 'All meals & premium drinks', 'Private vehicle & guide on safari', 'Internal flights', 'Special romantic touches (private dinners, spa treatment)', 'Pemba/Zanzibar transfers & activities'],
                'exclusions' => ['International flights', 'Visa', 'Gratuities'],
                'highlights' => [
                    ['title' => 'Exclusive Lodges', 'description' => 'Stay at some of Africa\'s most romantic properties.'],
                    ['title' => 'Privacy & Intimacy', 'description' => 'Tailored for couples seeking romance.'],
                    ['title' => 'Seamless Travel', 'description' => 'Effortless transfers and flights.'],
                ],
                 'itinerary' => [
                     ['title' => 'Day 1: Arrival JRO, fly to Serengeti', 'description' => 'Connect directly to Serengeti.', 'accommodation' => 'Four Seasons Safari Lodge Serengeti'],
                     ['title' => 'Day 2-4: Serengeti Romance', 'description' => 'Private game drives, sundowners, bush dinners.', 'accommodation' => 'Four Seasons Safari Lodge Serengeti'],
                     ['title' => 'Day 5: Fly to Pemba Island', 'description' => 'Fly via Arusha/Zanzibar to Pemba.', 'accommodation' => 'The Manta Resort (Underwater Room option)'],
                     ['title' => 'Day 6-10: Pemba Paradise', 'description' => 'Relax, dive, snorkel, enjoy island life.', 'accommodation' => 'The Manta Resort'],
                     ['title' => 'Day 11: Fly to Dar/ZNZ', 'description' => 'Connect for international flight.', 'accommodation' => null],
                     ['title' => 'Day 12: Departure Buffer', 'description' => 'Buffer day or depart.', 'accommodation' => null],
                 ],
                'destinations' => ['serengeti', 'pemba'],
                'safari_types' => ['luxury', 'honeymoon', 'beach', 'fly-in'],
                'min_pax' => 2,
                'max_pax' => 2,
                'is_featured' => true,
                'show_popular_tag' => false,
                'hero_image' => 'package-images/honeymoon_hero.jpg',
                'gallery_images' => [],
            ],
            [
                'title' => 'Photography Focused Safari',
                'short_description' => 'Maximize photo opportunities with a specialist guide.',
                'overview' => 'Designed for photographers, this safari offers modified vehicles, patient guides knowledgeable about light and positioning, and longer game drives in prime locations like Serengeti.',
                'price' => 5200.00,
                'duration' => '10 Days / 9 Nights',
                'location' => 'Serengeti, Ndutu (seasonal)',
                'rating_display' => '4.9 (8 Reviews)',
                'display_tags' => 'Photography, Specialist Guide, Wildlife',
                'status' => 'published',
                'inclusions' => ['Accommodation (often exclusive use camps/wings)', 'All meals', 'Specialist photo guide', 'Modified 4x4 vehicle (open roof, bean bags)', 'Extra luggage allowance for gear (check specifics)', 'Park fees', 'Internal flights'],
                'exclusions' => ['International flights', 'Visa', 'Camera gear', 'Gratuities'],
                'highlights' => [
                    ['title' => 'Photographer Guide', 'description' => 'Expert guidance for capturing the best shots.'],
                    ['title' => 'Optimized Vehicle', 'description' => 'Designed for stability and viewing angles.'],
                    ['title' => 'Prime Locations', 'description' => 'Focus on areas with high photographic potential.'],
                ],
                 'itinerary' => [
                     ['title' => 'Day 1: Arrival JRO, transfer Arusha', 'description' => 'Overnight Arusha for gear prep.', 'accommodation' => 'Arusha Coffee Lodge'],
                     ['title' => 'Day 2: Fly to Central Serengeti', 'description' => 'Fly to Seronera, meet photo guide.', 'accommodation' => 'Ubuntu Migration Camp (or similar photo-friendly camp)'],
                     ['title' => 'Day 3-5: Central Serengeti Photography', 'description' => 'Focus on big cats, diverse wildlife.', 'accommodation' => 'Ubuntu Migration Camp'],
                     ['title' => 'Day 6: Transfer to Ndutu (Seasonal: Dec-Mar)', 'description' => 'Drive or fly to Ndutu area for calving season.', 'accommodation' => 'Ndutu Safari Lodge'],
                     ['title' => 'Day 7-8: Ndutu Calving Season', 'description' => 'Predator action, vast herds, newborns.', 'accommodation' => 'Ndutu Safari Lodge'],
                     ['title' => 'Day 9: Fly back to Arusha', 'description' => 'Last morning shoot, fly to ARK/JRO.', 'accommodation' => 'Day room Arusha / Depart'],
                     ['title' => 'Day 10: Departure', 'description' => 'Depart JRO.', 'accommodation' => null],
                 ],
                'destinations' => ['serengeti', 'ndutu'],
                'safari_types' => ['photography', 'specialist', 'luxury', 'fly-in'],
                'min_pax' => 1,
                'max_pax' => 4,
                'is_featured' => false,
                'show_popular_tag' => false,
                'hero_image' => 'package-images/photo_hero.jpg',
                'gallery_images' => [],
            ],
            [
                'title' => 'Mount Meru Acclimatization Trek',
                'short_description' => '4-day trek up Mt Meru, ideal prep for Kilimanjaro.',
                'overview' => 'Trek Tanzania\'s second-highest peak, located in Arusha National Park. Offers fantastic wildlife viewing on lower slopes and serves as excellent acclimatization for Kilimanjaro.',
                'price' => 1100.00,
                'duration' => '4 Days / 3 Nights (on mountain)',
                'location' => 'Arusha National Park',
                'rating_display' => '4.5 (28 Reviews)',
                'display_tags' => 'Trekking, Acclimatization, Meru',
                'status' => 'published',
                'inclusions' => ['Park fees', 'Rescue fees', 'Hut accommodation on mountain', 'Meals on trek', 'Guide & porters', 'Transfers from Arusha/Moshi'],
                'exclusions' => ['Hotel before/after trek', 'Tips', 'Gear rental', 'Flights'],
                'highlights' => [
                    ['title' => 'Great Acclimatization', 'description' => 'Prepares you for Kilimanjaro\'s altitude.'],
                    ['title' => 'Wildlife on Trek', 'description' => 'See colobus monkeys, giraffes, buffaloes.'],
                    ['title' => 'Stunning Views', 'description' => 'Views of Kilimanjaro on clear days.'],
                ],
                'itinerary' => [
                    ['title' => 'Day 1: Momella Gate to Miriakamba Hut', 'description' => 'Start trek, wildlife viewing.', 'accommodation' => 'Miriakamba Hut'],
                    ['title' => 'Day 2: Miriakamba Hut to Saddle Hut', 'description' => 'Steeper ascent, acclimatization walk to Little Meru.', 'accommodation' => 'Saddle Hut'],
                    ['title' => 'Day 3: Summit Day & Return to Miriakamba', 'description' => 'Midnight start for Socialist Peak (summit), descend.', 'accommodation' => 'Miriakamba Hut'],
                    ['title' => 'Day 4: Descent to Momella Gate', 'description' => 'Descend through forest, transfer back.', 'accommodation' => null],
                ],
                'destinations' => ['arusha_np', 'meru'],
                'safari_types' => ['trekking', 'challenge', 'budget'],
                'min_pax' => 1,
                'max_pax' => 10,
                'is_featured' => false,
                'show_popular_tag' => false,
                'hero_image' => 'package-images/meru_hero.jpg',
                'gallery_images' => [],
            ],
            [
                'title' => 'Lake Natron & Ol Doinyo Lengai Trek',
                'short_description' => 'Visit the surreal Lake Natron and climb an active volcano.',
                'overview' => 'Journey to the remote Lake Natron, breeding ground for flamingos, nestled below the active volcano Ol Doinyo Lengai. Includes a challenging night trek up the "Mountain of God".',
                'price' => 1350.00,
                'duration' => '4 Days / 3 Nights',
                'location' => 'Lake Natron, Ol Doinyo Lengai',
                'rating_display' => '4.3 (12 Reviews)',
                'display_tags' => 'Remote, Adventure, Volcano, Trekking',
                'status' => 'published',
                'inclusions' => ['4x4 transport from Arusha', 'Basic tented camp/lodge accommodation', 'Meals', 'Local guide fees', 'Lengai climbing fee', 'Flamingo walk'],
                'exclusions' => ['Drinks', 'Tips', 'Gear rental', 'Flights'],
                'highlights' => [
                    ['title' => 'Lake Natron Flamingos', 'description' => 'See vast flocks of lesser flamingos (seasonal).'],
                    ['title' => 'Ol Doinyo Lengai Climb', 'description' => 'Challenging trek up an active volcano (requires fitness).'],
                    ['title' => 'Remote Landscape', 'description' => 'Stark, beautiful, and off-the-beaten-path.'],
                ],
                'itinerary' => [
                    ['title' => 'Day 1: Arusha to Lake Natron', 'description' => 'Long drive to Lake Natron, check into camp.', 'accommodation' => 'Lake Natron Camp (basic)'],
                    ['title' => 'Day 2: Lake Natron Exploration', 'description' => 'Walk to lake for flamingo viewing, visit waterfalls.', 'accommodation' => 'Lake Natron Camp'],
                    ['title' => 'Day 3: Ol Doinyo Lengai Climb', 'description' => 'Rest during day, midnight start for volcano climb.', 'accommodation' => 'Lake Natron Camp (return after climb)'],
                    ['title' => 'Day 4: Return to Arusha', 'description' => 'Descend Lengai (if climbed), drive back to Arusha.', 'accommodation' => null],
                ],
                'destinations' => ['natron', 'lengai'],
                'safari_types' => ['adventure', 'trekking', 'cultural', 'budget'],
                'min_pax' => 2,
                'max_pax' => 6,
                'is_featured' => false,
                'show_popular_tag' => false,
                'hero_image' => 'package-images/natron_hero.jpg',
                'gallery_images' => [],
            ],
             [
                'title' => 'Western Corridor Migration (Seasonal)',
                'short_description' => 'Follow the migration through the Grumeti region (May-July).',
                'overview' => 'Target the Great Migration herds as they move through the Serengeti\'s Western Corridor and face the challenges of the Grumeti River crocodiles. Typically a luxury focus.',
                'price' => 5500.00,
                'duration' => '6 Days / 5 Nights',
                'location' => 'Serengeti (Western Corridor / Grumeti)',
                'rating_display' => '4.9 (9 Reviews)',
                'display_tags' => 'Migration, Grumeti, Luxury, Seasonal',
                'status' => 'published',
                'inclusions' => ['Luxury Camp/Lodge accommodation', 'All meals & drinks', 'Park fees', 'Guide', '4x4 vehicle', 'Internal flights (Arusha-Grumeti-Arusha)'],
                'exclusions' => ['International flights', 'Visa', 'Gratuities'],
                'highlights' => [
                    ['title' => 'Grumeti River Crossings', 'description' => 'Witness dramatic river crossings (seasonal).'],
                    ['title' => 'Resident Wildlife', 'description' => 'Excellent resident game in the Grumeti area.'],
                    ['title' => 'Exclusive Camps', 'description' => 'Often utilizes high-end, secluded camps.'],
                ],
                 'itinerary' => [
                     ['title' => 'Day 1: Fly to Grumeti Airstrip', 'description' => 'Fly from Arusha to Grumeti, transfer to camp.', 'accommodation' => 'Singita Faru Faru Lodge (or similar)'],
                     ['title' => 'Day 2-4: Exploring Western Corridor', 'description' => 'Focus on migration movements and Grumeti River area.', 'accommodation' => 'Singita Faru Faru Lodge'],
                     ['title' => 'Day 5: Game Drives', 'description' => 'Further exploration, perhaps towards central Serengeti if herds moved.', 'accommodation' => 'Singita Faru Faru Lodge'],
                     ['title' => 'Day 6: Fly to Arusha', 'description' => 'Morning activity, fly back to Arusha.', 'accommodation' => null],
                 ],
                'destinations' => ['serengeti', 'grumeti'],
                'safari_types' => ['migration', 'luxury', 'seasonal', 'fly-in'],
                'min_pax' => 2,
                'max_pax' => 6,
                'is_featured' => false,
                'show_popular_tag' => false,
                'hero_image' => 'package-images/western_hero.jpg',
                'gallery_images' => [],
            ],
        ];

        foreach ($packages as $packageData) {
            if (empty($packageData['slug'])) {
                $packageData['slug'] = Str::slug($packageData['title']);
            }
            $packageData['is_featured'] = filter_var($packageData['is_featured'] ?? false, FILTER_VALIDATE_BOOLEAN);
            $packageData['show_popular_tag'] = filter_var($packageData['show_popular_tag'] ?? false, FILTER_VALIDATE_BOOLEAN);

            Package::create($packageData);
            $this->command->info("Created package: " . $packageData['title']);
        }

        $this->command->info('Package seeding completed.');
    }
} 